export const TOKEN = 'watchout-token'
export const CITIZEN_ID = 'watchout-citizen-id'
export const HANDLE = 'watchout-handle'
export const ALBUM_ID = 'watchout-album-id'
export const PERSONA_ID = 'watchout-persona-id'
export const ROLES = 'watchout-roles'
export const PERSONAS = 'watchout-personas'
