export const GOD = '*.god'
export const EDITOR = '*.editor'
export const AUTHOR = '*.author'
export const VOTER = '*.voter'
export const WITH_INFO = '*.with_info'
export const WITH_PAYMENT = '*.with_payment'
export const LINKS_EDITOR = '*.links_editor'
